security/urls.py
from django.conf.urls import patterns, url


view_prefix = ''
urlpatterns = patterns(
    view_prefix,
    url(r'^login$',  'security.views.login'),
    url(r'^logout$', 'security.views.logout'),
)

urls.py
from django.conf.urls import patterns, include, url


view_prefix = ''
urlpatterns = patterns(
    view_prefix,
    url(r'^$',          include('public.urls')),
    url(r'',            include('game.urls')),
    url(r'^admin/',     include('admin.urls')),
    url(r'^security/',  include('security.urls')),
    url(r'^api/',       include('api.urls')),
)

security/models.py
from django.db import models


class Account(models.Model):
    phone_number = models.IntegerField()
    pin_code = models.IntegerField()
    credit = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

security/forms.py
# coding: utf-8
from django import forms


class AccountForm(forms.Form):
    phone_number = forms.IntegerField(
                            max_value=99999999,
                            min_value=10000000)
    pin_code = forms.IntegerField(
                            max_value=9999,
                            min_value=1000,
                            widget=forms.PasswordInput)

security/views.py
# coding: utf-8
from decorators import check_login, render_to
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from forms import AccountForm
from models import Account


@render_to('security/index.html')
def login(request):
    data = {}
    if request.POST:
        form = AccountForm(request.POST)
        if form.is_valid():
            try:
                acc = Account.objects.get(
                        phone_number=form.cleaned_data['phone_number'],
                        pin_code=form.cleaned_data['pin_code'])
            except Account.DoesNotExist:
                msg = 'Утасны дугаар эсвэл Нууц үг буруу байна'
                form._errors["phone_number"] = form.error_class([msg])
            else:
                request.session['account_id'] = acc.id
                return redirect(reverse('game.views.dashboard'))

    else:
        form = AccountForm()

    data['form'] = form
    return data


@check_login
def logout(request):
    del request.session['account_id']
    return redirect(reverse('public.views.index'))

security/templates/security/index.html
{% extends "base.html" %}
{% block title %}login{% endblock %}
{% block content %}

<div class='row-fluid show-grid'>
  <div class='span6'>
    <h2>Нэвтрэx</h2>
    <form id='login-form' action="" method="POST">
      {% csrf_token %}
      {% if form.errors %}
        <div class='errorlist'>
          Утас эсвэл нууц үг буруу байна
        </div>
      {% endif %}
      <div>
        <label for="id_phone_number">Утас</label>
        <div class='controls'>
          {{ form.phone_number }}
        </div>
      </div>
      <div>
        <label for="id_pin_code">Нууц үг</label>
          <div class='controls'>
            {{ form.pin_code }}
        </div>
      </div>
      <input type="submit" value="Нэвтрэх" />
    </form>
  </div>

  <div class='span6'>
    <h2>Бүртгүүлэх</h2>
    <div class="instruction">
      Хэрэв та бүртгүүлээгүй бол бидэнд мессеж илгээнэ үү! Бид
      танд нэвтрэх нууц дугаарыг илгээх болно.
    </div>
  </div>
</div>

{% endblock %}
{% block js-init %}
  $("#id_phone_number").focus()
{% endblock %}

{# vim: set ts=2 sw=2 sts=2 fdn=4 : #}